### ISSUE TITLE
My Server doesn't have a server.out file

### ISSUE THREAD

**Issue by Steven121314** [Jaskowicz1/Factorio-Discord-Relay#7]
My server doesn't have a server.out file. I'm in AppData\Roaming\Factorio and there is no server.out. Am I just missing something?

**Comment by Jaskowicz1** [comment]
Hi there, I'm assuming you're trying to use this with a server hosted from your physical factorio game. You need a headless server in order to use this.

If that's not the case then please do feel free to comment again and I'll try help you further.

**Comment by Steven121314** [comment]
Are there other types of headless servers? I'm using the one that came with the game.

**Comment by Jaskowicz1** [comment]
> Are there other types of headless servers? I'm using the one that came with the game.

There are not, no, which makes this weird (maybe they changed the file?). I thought you were trying to run a server as if you had the game open (like a steam session).

I'm currently unwell but as soon as I'm better I'll have a close look and try replicate the issue!

**Comment by Steven121314** [comment]
Yeah, I'm using the headless server and I've checked all the settings to see if there's something that would cause this file to not be created, but I can't find anything. The Relay, besides that works fine. The bot activates and discord messages show up in game. Just not vice-versa. I can provide any files or screenshots you need. I hope you get feeling better soon!

**Comment by Jaskowicz1** [comment]
Hi there, sorry, I ended up being in the hospital for a bit and then just relaxing for a couple of weeks, all good now!

I'll look into this asap!

**Comment by Jaskowicz1** [comment]
Okay, you'll need to add `--console-log <file_path>` to your arguments for the server (for example: `factorio.exe --start-server .saves/save.zip --console-log .data/console.log`. That will act as your server.out file and you can then feed it to the config!
